//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.NhanVien.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.NhanVien.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code emp duplicate.
        /// </summary>
        public static string Dev_employee_Duplicate {
            get {
                return ResourceManager.GetString("Dev_employee_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Fail.
        /// </summary>
        public static string DevMsg_Delete_Fail {
            get {
                return ResourceManager.GetString("DevMsg_Delete_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on the server.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Fail.
        /// </summary>
        public static string DevMsg_Insert_Fail {
            get {
                return ResourceManager.GetString("DevMsg_Insert_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Fail.
        /// </summary>
        public static string DevMsg_Update_Fail {
            get {
                return ResourceManager.GetString("DevMsg_Update_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Error.
        /// </summary>
        public static string DevMsg_Validate {
            get {
                return ResourceManager.GetString("DevMsg_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống..
        /// </summary>
        public static string Employee_EmployeeCode_Duplicate {
            get {
                return ResourceManager.GetString("Employee_EmployeeCode_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string More_Info {
            get {
                return ResourceManager.GetString("More_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_code_Update.
        /// </summary>
        public static string Proc_Code_Update {
            get {
                return ResourceManager.GetString("Proc_Code_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteByID.
        /// </summary>
        public static string Proc_Delete {
            get {
                return ResourceManager.GetString("Proc_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_DeleteMultiple.
        /// </summary>
        public static string Proc_employee_DeleteBatch {
            get {
                return ResourceManager.GetString("Proc_employee_DeleteBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_filter.
        /// </summary>
        public static string Proc_employee_filter {
            get {
                return ResourceManager.GetString("Proc_employee_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_getMaxCode.
        /// </summary>
        public static string Proc_employee_getMaxCode {
            get {
                return ResourceManager.GetString("Proc_employee_getMaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetByID.
        /// </summary>
        public static string Proc_GetByID {
            get {
                return ResourceManager.GetString("Proc_GetByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Insert.
        /// </summary>
        public static string Proc_Insert {
            get {
                return ResourceManager.GetString("Proc_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_code_GetNew.
        /// </summary>
        public static string Proc_New_Code {
            get {
                return ResourceManager.GetString("Proc_New_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Update.
        /// </summary>
        public static string Proc_Update {
            get {
                return ResourceManager.GetString("Proc_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên mới phải lớn hơn mã nhân viên cũ.
        /// </summary>
        public static string UserMsg_Code_LessThan {
            get {
                return ResourceManager.GetString("UserMsg_Code_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thất bại.
        /// </summary>
        public static string UserMsg_Delete_Fail {
            get {
                return ResourceManager.GetString("UserMsg_Delete_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất 1 đơn vị.
        /// </summary>
        public static string UserMsg_DepartmentID_NOTNULL {
            get {
                return ResourceManager.GetString("UserMsg_DepartmentID_NOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống.
        /// </summary>
        public static string UserMsg_employee_Duplicate {
            get {
                return ResourceManager.GetString("UserMsg_employee_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra. Vui lòng liên hệ MISA.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bản ghi thất bại.
        /// </summary>
        public static string UserMsg_Insert_Fail {
            get {
                return ResourceManager.GetString("UserMsg_Insert_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại..
        /// </summary>
        public static string UserMsg_Update_Fail {
            get {
                return ResourceManager.GetString("UserMsg_Update_Fail", resourceCulture);
            }
        }
    }
}
